CREATE TABLE users (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    profile_complete_percentage INTEGER DEFAULT 0,
    avatar_url TEXT,
    location TEXT,
    bio TEXT,
    website_url TEXT,
    github_url TEXT,
    linkedin_url TEXT,
    twitter_url TEXT,
    whatsapp_url TEXT,
    tagline TEXT,
    is_email_verified BOOLEAN DEFAULT 0,
    email_verified_at DATETIME
, role TEXT, categories_json TEXT, looking_for_json TEXT, skills_json TEXT, cover_photo_url TEXT)